---
- name: Установка Docker и Docker Compose
  hosts: all  # Указываем, что плейбук будет выполняться на всех хостах из инвентаря
  become: true  # Выполнять задачи с повышенными привилегиями (sudo)
  vars_prompt:
    - name: ansible_password
      prompt: "Введите пароль для подключения к хостам"
      private: yes

  tasks:
    - name: Проверка подключения к хостам
      ping:

  roles:
    - role: install_docker  # Указываем роль, которая будет использоваться для установки Docker
