- name: pass
  hosts: all

  vars_prompt:
    - name: ansible_password
      prompt: Пароль для подключения
      private: yes

##########################################################################################################################################################################################################
# Установка символической ссылки на папку 1С ПРЕДПРИЯТИЯ
- name: installing symlink to path with 1С server
  hosts: serv1C

  roles:
    - create_change_symlink # Установка службы удаленного администрирования 1С
