- name: pass
  hosts: all

  vars_prompt:
    - name: ansible_password
      prompt: Пароль для подключения
      private: yes

##########################################################################################################################################################################################################
#УСТАНОВКА УТИЛИТЫ ЛИЦЕНЗИРОВАНИЯ 1C И JRE
- name: install licensing 1C utility and JRE 
  hosts: serv1C

  vars:
    jre_dir_dest: /tmp/ansible-temp-files/deb/for_jre # директория куда нужно копировать файл установки JRE
    jre_file_name: "bellsoft_jre11.0.20_8_linux_amd64_full.deb" # Наименование файла deb с пакетом
    jre_package: "/ansible/distr/deb/for_jre/{{ jre_file_name }}" # директория, где хранится исходный файл JRE (на хосте, где запускается сам ansible playbook)
    tmp_dir: /tmp/ansible-tmp-files
    
    # УСТАНОВИ ФЛАГИ В defaults ролей
    #add_JAVA_HOME_env_to_PATH: true # Флаг нужно или нет добавить переменную JAVA_HOME в PATH
    #add_ring_env_to_PATH: true # Флаг нужно или нет добавить переменную ring в PATH
    # Помни переменные окружения требуют перезапуска сессии пользователя, чтобы вступить в силу

  roles:
    - install_JRE # Установка пакета JRE
    - install_lictools # Установка пакета с инструемнтами лицензирования 1C (ring license)

##########################################################################################################################################################################################################