ServerActive=some_host_ip:10051
Server=some_host_ip
AllowKey=system.run[*]
Timeout=30

ListenPort=10050

Include=/etc/zabbix/zabbix_agent2.d
PidFile=/var/run/zabbix/zabbix_agent2.pid
LogFile=/var/log/zabbix/zabbix_agent2.log
LogFileSize=1

UnsafeUserParameters=1
DebugLevel=3
